sudo: false
language: node_js
cache:
  directories:
    - node_modules
env:
  - ApiKey=$API_KEY
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run build