sudo: false
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
env:
  - ApiKey=$API_KEY
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"